application:
  env: dev

database:
  dev:
    name: BDTCCDEV
    username: postgres
    password: 123456
    host: localhost
    port: 5432
  prd:
    name: BDTCCPRD
    username: postgres
    password: 123456
    host: localhost
    port: 5432
