application:
    env: dev
  
nominatim-api:
    local:
        url: http://localhost:8080/
        enabled: False

overpass-api:
    local:
        url: http://localhost:80/api
        enabled: False

database:
    dev:
        name: BDTCCDEV
        username: postgres
        password: 123456
        host: localhost
        port: 5432
    prd:
        name: BDTCCPRD
        username: postgres
        password: 123456
        host: localhost
        port: 5432
