version: "3.9"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.4
        ports:
            - "8080:8080"
        environment:
            PBF_URL: https://download.geofabrik.de/south-america/brazil-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/south-america/brazil-updates/
            NOMINATIM_PASSWORD: 123456
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 1gb

    overpass:
        container_name: overpass
        image: wiktorn/overpass-api:0.7.56.9
        ports:
          - "12345:80"
        environment:
          - OVERPASS_META=yes
          - OVERPASS_MODE=init
          - OVERPASS_PLANET_URL=http://download.geofabrik.de/south-america/brazil-latest.osm.bz2
          - OVERPASS_DIFF_URL=http://download.openstreetmap.fr/replication/south-america/brazil/minute/
          - OVERPASS_UPDATE_SLEEP=3600
          - OVERPASS_USE_AREAS=false
        volumes:
          - overpass-db:/db
        healthcheck:
          test: ["CMD-SHELL", "curl --noproxy '*' -qf 'http://localhost/api/interpreter?data=[out:json];node(1);out;' | jq '.generator' | grep -q Overpass || exit 1"]
          start_period: 48h

volumes:
    nominatim-data:
    overpass-db:
  