from enum import Enum

class EtapaProcessamentoEnum(Enum):

    CARGA_INICIAL = 1
    GERACAO_MALHA_HEXAGONAL = 2
    EXTRACAO_AMENIDADES = 3
    CALCULO_MATRIZ_TEMPO_VIAGEM = 4
    CALCULO_INDICE_MUNICIPIO = 5
    CALCULO_INDICE_UNIDADE_FEDERATIVA = 6